name: Fill Secrets and Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  prepare-and-trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fill secrets in application.yaml
        run: |
          sed -i "s|\${MYSQL_URL}|${{ secrets.MYSQL_URL }}|g" src/main/resources/application.yaml
          sed -i "s|\${USERNAME}|${{ secrets.USERNAME }}|g" src/main/resources/application.yaml
          sed -i "s|\${PASSWORD}|${{ secrets.PASSWORD }}|g" src/main/resources/application.yaml
          git config --local user.email "etkl8888@naver.com"
          git config --local user.name "seonghoJoo"
          git commit -am "Fill secrets" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAT }}@github.com/HAECCS/api-server.git

      - name: Trigger Jenkins with job token
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/jenkins/job/api-server/build?token=${{ secrets.JENKINS_JOB_TOKEN }}" \
          --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }}
