name: Fill Secrets and Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  prepare-and-trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fill secrets in application.yaml get secret
        run: |
          echo "${{ secrets.GH_PAT }}"
          

      - name: Trigger Jenkins with job token let's build
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/jenkins/job/api-server/build?token=${{ secrets.JENKINS_JOB_TOKEN }}" \
          --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }}
